# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6006b0d8f39b8f59fdb0385d36d6f0e36d77b22c0b66044b937333c1cebf0325924a3927c54d27e3bbe2f3059a0ea6e8720e989f2b8981c9d51964d4bfbd5f

test:
  secret_key_base: 0e7d9ad82cba913d1e0ec13e104039651032c15a4890332b4f90842bb3ac417ba2c54f3f12de6a082659c780e24461f4e25532edddb50c6fa50c56a1e83b8f68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
